spring:
  profiles: default
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dims?serverTimezone=Australia/Sydney
    username: dims
    password: dims
    test-on-borrow: true
    validation-query: SELECT 1

